cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: C:/Users/rafad/OneDrive/Imagens/TestApi
security:
  jwt:
    token:
    secret-key: 53cr37
    expire-length: 3600000
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB
    open-in-view: false
springdoc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true