name: Continuos Integration Github Action

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
        cache: maven
    - name: Setup Java JDK
      uses: action/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Build apllication Jar
      working-directory: ./SpringJavaRest
      run: mvn clean package -DskipTests
      
    - name: Docker Compose Build
      working-directory: ./SpringJavaRest/Docker/
      run: docker compose building

    - name: Push to Docker Hub Container Registry
      run: docker tag ${{ secrets.DOCKER_USERNAME}}/spring-boot:lastest ${{ secrets.DOCKER_USERNAME}}/spring-boot:${{ github.run_id }}

          docker push ${{ secrets.DOCKER_USERNAME}}/spring-boot/spring-boot:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME}}/spring-boot/spring-boot:latest
